### ISSUE TITLE
Set correct HOME directory for user running bamboo

### ISSUE THREAD

**Issue by blop** [cptactionhank/docker-atlassian-bamboo#13]
Bamboo is currently running as daemon, but has /sbin/ has default HOME directory, which is not writable by daemon.
`daemon:x:2:2:daemon:/sbin:/sbin/nologin
`
This cause some issues with builds that requires a writable HOME.
Tools like Gradle needs to cache information in the HOME directory.

Could you setup the HOME to something writable, or better, to /var/atlassian/bamboo/.
I'd suggest creating a "bamboo" user then.

**Comment by Daywalker999** [comment]
Ran into a similar problem today where bamboo wanted to create ssh keys and and known hosts in /sbin/.ssh.
+1 for the Pullrequest

**Comment by claflico** [comment]
Looks like we can't use the Java based Build Specs either because it tries to check out the repo to /sbin/.m2/repository.
